/**
 * Interactive first-run setup for the foundry-samples Playwright suite.
 *
 * Reads internal/playwright-tests/.env.local (gitignored). When required values are
 * missing and stdin is a TTY, prompts the developer once and persists the
 * answers. On non-TTY environments (e.g. CI) throws with the list of missing
 * variables so the failure is actionable.
 *
 * Required:
 *   - AI_FOUNDRY_PROJECT_URI       ARM resource path of the Foundry project
 *
 * Optional:
 *   - AI_FOUNDRY_EXTENSION_PATH    Path to a built ai-foundry-for-vscode
 *                                  working tree. When unset, the launcher
 *                                  installs the published extension from
 *                                  the VS Code marketplace.
 *
 * The project location is resolved automatically via ARM.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { DefaultAzureCredential } from '@azure/identity';
import { initFixture, parseProjectUri, type FixtureTarget } from './target';

const ENV_FILE = path.join(__dirname, '..', '.env.local');

const REQUIRED_VARS = ['AI_FOUNDRY_PROJECT_URI'] as const;

type RequiredVar = (typeof REQUIRED_VARS)[number];

function loadEnvFile(): Record<string, string> {
    if (!fs.existsSync(ENV_FILE)) {
        return {};
    }
    const out: Record<string, string> = {};
    const raw = fs.readFileSync(ENV_FILE, 'utf-8');
    for (const line of raw.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) {
            continue;
        }
        const eq = trimmed.indexOf('=');
        if (eq < 0) {
            continue;
        }
        const key = trimmed.slice(0, eq).trim();
        let value = trimmed.slice(eq + 1).trim();
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
        }
        out[key] = value;
    }
    return out;
}

function persistEnvFile(values: Record<string, string>): void {
    fs.mkdirSync(path.dirname(ENV_FILE), { recursive: true });
    const lines = [
        '# Auto-generated by internal/playwright-tests/fixtures/configPrompt.ts.',
        '# Edit values here or delete this file to be re-prompted on next run.',
        ''
    ];
    for (const [k, v] of Object.entries(values)) {
        lines.push(`${k}=${v}`);
    }
    fs.writeFileSync(ENV_FILE, lines.join('\n') + '\n', { mode: 0o600 });
}

async function promptForMissing(missing: RequiredVar[]): Promise<Record<string, string>> {
    const rl = readline.createInterface({ input, output });
    const answers: Record<string, string> = {};
    try {
        // eslint-disable-next-line no-console
        console.log('\n[playwright-tests] First-run setup. Saved to internal/playwright-tests/.env.local.\n');
        for (const key of missing) {
            const hint =
                '  /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.CognitiveServices/accounts/<acct>/projects/<proj>\n  (a leading "/resource" is OK)';
            // eslint-disable-next-line no-console
            console.log(`${key}\n${hint}`);
            let value = '';
            while (!value) {
                value = (await rl.question(`> `)).trim();
                if (!value) {
                    // eslint-disable-next-line no-console
                    console.log('  (required — please enter a value)');
                }
            }
            answers[key] = value;
            // eslint-disable-next-line no-console
            console.log('');
        }
    } finally {
        rl.close();
    }
    return answers;
}

async function resolveProjectLocation(parsed: ReturnType<typeof parseProjectUri>): Promise<string> {
    const credential = new DefaultAzureCredential(
        process.env.AI_FOUNDRY_TENANT_ID ? { tenantId: process.env.AI_FOUNDRY_TENANT_ID } : undefined
    );
    const token = await credential.getToken('https://management.azure.com/.default');
    if (!token) {
        throw new Error('Could not acquire ARM token for project location lookup. Run `az login` and retry.');
    }
    const url =
        `https://management.azure.com/subscriptions/${parsed.subscriptionId}` +
        `/resourceGroups/${parsed.resourceGroup}` +
        `/providers/Microsoft.CognitiveServices/accounts/${parsed.accountName}` +
        `?api-version=2023-05-01`;
    const resp = await fetch(url, { headers: { Authorization: `Bearer ${token.token}` } });
    if (!resp.ok) {
        throw new Error(
            `Failed to look up project location (${resp.status} ${resp.statusText}). ` +
                `Verify AI_FOUNDRY_PROJECT_URI points to an account you have access to.`
        );
    }
    const body = (await resp.json()) as { location?: string };
    if (!body.location) {
        throw new Error(`Account response did not include a location field. URL: ${url}`);
    }
    return body.location;
}

function validateExtensionPath(extensionPath: string): string {
    const resolved = path.resolve(extensionPath);
    const distEntry = path.join(resolved, 'dist', 'extension.js');
    const distWebview = path.join(resolved, 'dist', 'webview-ui', 'src', 'index.js');
    if (!fs.existsSync(distEntry) || !fs.existsSync(distWebview)) {
        throw new Error(
            `AI_FOUNDRY_EXTENSION_PATH does not contain a built extension at ${resolved}.\n` +
                `Missing one or more of:\n  - ${distEntry}\n  - ${distWebview}\n\n` +
                'Run (from the ai-foundry-for-vscode repo root):\n  npm run build:playwright\n\n' +
                'Or unset AI_FOUNDRY_EXTENSION_PATH to use the marketplace extension instead.'
        );
    }
    return resolved;
}

export async function ensureFixtureConfigured(): Promise<FixtureTarget> {
    const fileValues = loadEnvFile();
    for (const [k, v] of Object.entries(fileValues)) {
        if (!process.env[k]) {
            process.env[k] = v;
        }
    }

    const missing = REQUIRED_VARS.filter((k) => !process.env[k]);
    if (missing.length > 0) {
        if (!input.isTTY) {
            throw new Error(
                `Missing required env vars: ${missing.join(', ')}. ` +
                    `Set them in the environment or in internal/playwright-tests/.env.local. ` +
                    `Run the suite locally once with a TTY to be prompted.`
            );
        }
        const answers = await promptForMissing(missing);
        for (const [k, v] of Object.entries(answers)) {
            process.env[k] = v;
        }
        const merged = { ...fileValues, ...answers };
        persistEnvFile(merged);
    }

    const parsed = parseProjectUri(process.env.AI_FOUNDRY_PROJECT_URI as string);
    const extensionPath = process.env.AI_FOUNDRY_EXTENSION_PATH
        ? validateExtensionPath(process.env.AI_FOUNDRY_EXTENSION_PATH)
        : undefined;
    const location = await resolveProjectLocation(parsed);
    const target: FixtureTarget = {
        ...parsed,
        location,
        extensionPath
    };
    initFixture(target);
    return target;
}
